// P-ERR

func main() {}

dynamic func test() {}