// P-ERR

func main() {}

public private func test() {}