// P-ERR

func number<T E>(a: T) {}

func main() {
}