// P-ERR

func number[T: Number E](a: T) {}

func main() {
}