// C-ERR

func main() {
    print(me)
}
