// C-ERR

func main() {
    print(Test.ok)
}

class Test {
    val ok = 5
}