// C-ERR

func main() {
    printnum(Test.ok)
}

class Test {
    val ok = 5
}