// ERR

fun test(s: String) {
    print(s);
}

func main() {
    test()
}