// C-ERR

func main() {
}

func a() {
}

func c() -> a {
    a
}