// C-ERR

func main() {
}

func a(a: Range) {

}